[supervisord]
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid
childlogdir=/tmp/

[program:app]
command=python3 /home/ec2-user/vigilator.ai/flask-backend/app.py
autostart=true
autorestart=true
stderr_logfile=/tmp/app.err.log
stdout_logfile=/tmp/app.out.log

[program:content]
command=python3 /home/ec2-user/vigilator.ai/flask-backend/content.py
autostart=true
autorestart=true
stderr_logfile=/tmp/content.err.log
stdout_logfile=/tmp/content.out.log

[program:trancocheck]
command=python3 /home/ec2-user/vigilator.ai/flask-backend/trancocheck.py
autostart=true
autorestart=true
stderr_logfile=/tmp/tranco.err.log
stdout_logfile=/tmp/tranco.out.log

[program:central_api]
command=python3 /home/ec2-user/vigilator.ai/flask-backend/central_api.py
autostart=true
autorestart=true
stderr_logfile=/tmp/central.err.log
stdout_logfile=/tmp/central.out.log
